MasrafTakipMVCProje/Controllers/HarcamaController.cs
using MasrafTakipMVCProje.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MasrafTakipMVCProje.Controllers
{
    public class HarcamaController : Controller
    {
        private readonly MasrafTakipContext context;
        public HarcamaController(MasrafTakipContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var harcama = context.Harcamalar.Include(p => p.Personeller).ToList();
            return View(harcama);
        }

        public IActionResult Create()
        {
            ViewBag.PersonelId = context.Personeller
        .Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Adi + " " + s.Soyadi }).ToList();


            return View(new Harcama());
        }

        [HttpPost]
        public IActionResult Create(Harcama harcama)
        {
            if (ModelState.IsValid)
            {
                context.Add(harcama);
                context.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.PersonelId = context.Personeller
       .Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Adi + " " + s.Soyadi }).ToList();
            return View(harcama);
        }
    }
}

MasrafTakipMVCProje/Controllers/HarcamaDetayController.cs
using MasrafTakipMVCProje.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MasrafTakipMVCProje.Controllers
{
    public class HarcamaDetayController : Controller
    {
        private readonly MasrafTakipContext context;
        public HarcamaDetayController(MasrafTakipContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var harcamaDetaylari = context.HarcamaDetaylari.Include(s => s.Harcama).Include(s => s.HarcamaTipleri).ToList();
            return View(harcamaDetaylari);
        }

        public IActionResult Create()
        {

            ViewBag.HarcamaId = new SelectList(context.Harcamalar, "Id", "Id");

            ViewBag.HarcamaTipId = context.HarcamaTipleri
             .Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Baslik }).ToList();

            return View(new HarcamaDetay());
        }

        [HttpPost]
        public IActionResult Create(HarcamaDetay harcamaDetaylari)
        {
            if (ModelState.IsValid)
            {
                var harcamaDetay = new HarcamaDetay
                {
                    Tutar = harcamaDetaylari.Tutar,
                    HarcamaId = harcamaDetaylari.HarcamaId,
                    HarcamaTipiId = harcamaDetaylari.HarcamaTipiId,
                    Aciklama = harcamaDetaylari.Aciklama
                };

                context.Add(harcamaDetay);
                context.SaveChanges();



                //context.Add(harcamaDetaylari);
                //context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(harcamaDetaylari);
        }
    }
}

MasrafTakipMVCProje/Controllers/HarcamaTipiController.cs
using MasrafTakipMVCProje.Models;
using Microsoft.AspNetCore.Mvc;

namespace MasrafTakipMVCProje.Controllers
{
    public class HarcamaTipiController : Controller
    {
        private readonly MasrafTakipContext context;
        public HarcamaTipiController(MasrafTakipContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var harcamaTipis = context.HarcamaTipleri.ToList();

            return View(harcamaTipis);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(HarcamaTipi harcamaTipi)
        {
            if (ModelState.IsValid)
            {
                context.Add(harcamaTipi);
                context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(harcamaTipi);
        }
    }
}

MasrafTakipMVCProje/Controllers/PersonelController.cs
using MasrafTakipMVCProje.Models;
using Microsoft.AspNetCore.Mvc;

namespace MasrafTakipMVCProje.Controllers
{
    public class PersonelController : Controller
    {
        private readonly MasrafTakipContext context;
        public PersonelController(MasrafTakipContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var personeller = context.Personeller.ToList();
            return View(personeller);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Personel personel)
        {
            if (ModelState.IsValid)
            {
                context.Add(personel);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(personel);
        }
    }
}

MasrafTakipMVCProje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MasrafTakipMVCProje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MasrafTakipMVCProje.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MasrafTakipMVCProje</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personel" asp-action="Index">Personeller</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Harcama" asp-action="Index">Harcamalar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HarcamaTipi" asp-action="Index">Harcama Tipleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HarcamaDetay" asp-action="Index">Harcama Detayları</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MasrafTakipMVCProje - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MasrafTakipMVCProje/Views/Shared/_LoginLayout.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MasrafTakipMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MasrafTakipMVC.styles.css" asp-append-version="true" />
</head>

<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>